# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hydrogen
email: info@hydrogen-music.com
description: > # this means to ignore newlines until "baseurl:"
    The digital home of the advanced drum machine.
#baseurl: "/hydrogen" # the subpath of your site, e.g. /blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://hydrogen-music.com" # the base hostname & protocol for your site
github_username:  hydrogen-music/hydrogen

#permalink: /hydrogen/:title
permalink: :title

#Seperator
excerpt_separator: "\n\n"

# Build settings
markdown: kramdown
#theme: hydrogen
