#! /bin/bash

BUILDER=${BUILDER:-cmake}
QTDIR=${QTDIR:-/usr/lib/qt}
VERBOSE=${VERBOSE:-0}
CMAKE_OPTIONS="-DWANT_DEBUG=1 -DWANT_JACK=1 -DWANT_ALSA=1 -DWANT_LIBARCHIVE=1"
CMAKE_OPTIONS="${CMAKE_OPTIONS} -DWANT_OSS=1 -DWANT_PORTAUDIO=1 -DWANT_PORTMIDI=1 -DWANT_LASH=1 -DWANT_LRDF=1 -DWANT_FLAC=1"
CMAKE_OPTIONS_="${CMAKE_OPTIONS} -DWANT_COREAUDIO=1 -DWANT_COREMIDI=1"
MAKE_OPTS="-j 2"
H2FLAGS="-V0x7"

find . -name '*~' -exec rm '{}' \;
rm libs/hydrogen/include/hydrogen/config.h 2>/dev/null

function scons_clean() {
    echo -e " * clean scons files\n"
    rm -fr scache.conf scons_cache .sconf_temp .sconsign.dblite qt4.pyc config.log hydrogen libhydrogen.a
}

function scons_rm() {
    scons_clean
    echo -e " * rm scons files\n"
    find . -name '*.a' -exec rm '{}' \;
    find . -name '*.o' -exec rm '{}' \;
    find . -name 'ui_*' -exec rm '{}' \;
    find . -name 'moc_*' -exec rm '{}' \;
}

function scons_make() {
    echo -e " * scons make\n" && scons || exit 1
}

function scons_doc() {
    echo -e " * sorry, no can do\n"
}

function scons_graph() {
    echo -e " * sorry, no can do\n"
}

function scons_help() {
    echo -e " * scons make\n" && scons
}

function scsons_exec() {
    echo -e " * execute hydrogen\n" && ./hydrogen $H2FLAGS
}

function cmake_clean() {
    echo -e " * clean cmake files\n" && rm build/CMakeCache.txt 2>/dev/null
}

function cmake_rm() {
    echo -e " * rm cmake files\n" && rm -fr build 2>/dev/null
}

function cmake_make() {
    echo -e " * cmake make\n"
    if [ ! -d build ]; then
        mkdir build
    fi
    cd build
    if [ ! -e CMakeCache.txt ]; then
        cmake ${CMAKE_OPTIONS} ..
    fi
    if [ $VERBOSE -eq 1 ]; then
        VERBOSE=1 make $MAKE_OPTS || exit 1
    else
        make $MAKE_OPTS || exit 1
    fi
}

function cmake_graph() {
    echo -e " * cmake graphviz\n"
    if [ ! -d build ]; then
        mkdir build
    fi
    cd build && cmake --graphviz=cmake.dot .. && dot -Tpng -o cmake_dep.png cmake.dot
}

function cmake_doc() {
    if [ -d build ]; then
        cd build && make doc
    fi
}

function cmake_help() {
    echo -e " * cmake help\n"
    if [ ! -d build ]; then
        mkdir build
    fi
    cd build && cmake -L ..
}

function cmake_exec() {
    echo -e " * execute hydrogen\n" && ./gui/hydrogen $H2FLAGS
}

echo -e "used builder : ${BUILDER}"
if [ $# -eq 0 ]; then
    echo "usage $0 [cmds list]"
    echo "cmds may be"
    echo "   r or rm     => all built, temp and cache files"
    echo "   c or clean  => remove cache files"
    echo "   m or make   => launch the build process"
    echo "   d or doc    => build html documentation"
    echo "   g or graph  => draw a dependecies graph"
    echo "   h or help   => show the build options"
    echo "   x or exec   => execute hydrogen"
    exit 1
fi

for arg in $@; do
    case $arg in
        "c")
            cmd="${BUILDER}_clean"
            ;;
        "clean")
            cmd="${BUILDER}_${arg}"
            ;;
        "r")
            cmd="${BUILDER}_rm"
            ;;
        "rm")
            cmd="${BUILDER}_${arg}"
            ;;
        "m")
            cmd="${BUILDER}_make"
            ;;
        "make")
            cmd="${BUILDER}_${arg}"
            ;;
        "g")
            cmd="${BUILDER}_graph"
            ;;
        "graph")
            cmd="${BUILDER}_${arg}"
            ;;
        "d")
            cmd="${BUILDER}_doc"
            ;;
        "doc")
            cmd="${BUILDER}_${doc}"
            ;;
        "h")
            cmd="${BUILDER}_help"
            ;;
        "help")
            cmd="${BUILDER}_${arg}"
            ;;
        "x")
            cmd="${BUILDER}_exec"
            ;;
        "exec")
            cmd="${BUILDER}_${arg}"
            ;;
        *)
         echo "unknown command ${arg}" && exit 1
     esac
     $cmd
done

cp gui/hydrogen ../hydrogen

#grep -l -R SUPPORT gui/ | xargs sed -i -e 's/ \(.*\)_SUPPORT/ HYDROGEN_\1_SUPPORT/'
#grep -l -R 'include "config.h"' gui/ | xargs sed -i -e '/include "config.h"help
