#include <core/Helpers/Xml.h>
#include <core/Basics/Drumkit.h>
#include <core/Basics/DrumkitComponent.h>
#include <core/Basics/Instrument.h>
#include <core/Basics/InstrumentComponent.h>
#include <core/Basics/InstrumentLayer.h>
#include <core/Basics/InstrumentList.h>
#include <core/Basics/Sample.h>
#include <core/Preferences.h>
#include <core/Basics/Playlist.h>
#include <core/Basics/Pattern.h>
#include <core/Basics/PatternList.h>
#include <core/Basics/AutomationPath.h>
#include <core/Basics/Song.h>
#include <core/Hydrogen.h>
#include <core/AudioEngine.h>
#include <core/CoreActionController.h>
#include <core/EventQueue.h>
#include <core/H2Exception.h>
#include <core/MidiAction.h>
#include <core/MidiAction.h>
#include <core/MidiAction.h>
#include <core/Timeline.h>
#include <core/Version.h>
#include <core/Version.h>
#include <core/FX/Effects.h>
#include <core/FX/LadspaFX.h>
#include <core/IO/AlsaAudioDriver.h>
#include <core/IO/AlsaMidiDriver.h>
#include <core/IO/AudioOutput.h>
#include <core/IO/CoreMidiDriver.h>
#include <core/IO/DiskWriterDriver.h>
#include <core/IO/FakeDriver.h>
#include <core/IO/JackAudioDriver.h>
#include <core/IO/JackMidiDriver.h>
#include <core/IO/MidiInput.h>
#include <core/IO/MidiCommon.h>
#include <core/IO/MidiOutput.h>
#include <core/IO/MidiCommon.h>
#include <core/IO/NullDriver.h>
#include <core/IO/PortAudioDriver.h>
#include <core/IO/PortMidiDriver.h>
#include <core/IO/PulseAudioDriver.h>
#include <core/IO/TransportInfo.h>
#include <core/Lash/LashClient.h>
#include <core/Lilipond/Lilypond.h>
#include <core/Sampler/Sampler.h>
#include <core/Synth/Synth.h>
#include <qtreset.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>
#include <pybind11/numpy.h>
#include <qtcasters.h>
