#! /bin/bash

QTDIR=${QTDIR:-/usr/lib/qt}
VERBOSE=${VERBOSE:-0}
CMAKE_OPTIONS="-DWANT_DEBUG=1 -DWANT_JACK=1 -DWANT_ALSA=1 -DWANT_LIBARCHIVE=1 -DWANT_RUBBERBAND=1"
CMAKE_OPTIONS="${CMAKE_OPTIONS} -DWANT_OSS=1 -DWANT_PORTAUDIO=1 -DWANT_PORTMIDI=1 -DWANT_LASH=1 -DWANT_LRDF=1"
CMAKE_OPTIONS_="${CMAKE_OPTIONS} -DWANT_COREAUDIO=1 -DWANT_COREMIDI=1"
MAKE_OPTS="-j 2"
H2FLAGS="-V0xf"

find . -name '*~' -exec rm '{}' \;

function cmake_init() {
    echo -e " * cmake init\n"
    if [ ! -d build ]; then
        mkdir build || exit 1
    fi
    cd build || exit 1
    if [ ! -e CMakeCache.txt ]; then
        cmake ${CMAKE_OPTIONS} .. || exit 1
    fi
    cd .. || exit 1
}

function cmake_clean() {
    echo -e " * clean cmake files\n" && rm build/CMakeCache.txt 2>/dev/null
}

function cmake_rm() {
    echo -e " * rm cmake files\n" && rm -fr build 2>/dev/null
}

function cmake_make() {
    cmake_init
    echo -e " * cmake make\n" && cd build || exit 1
    if [ $VERBOSE -eq 1 ]; then
        VERBOSE=1 make $MAKE_OPTS || exit 1
    else
        make $MAKE_OPTS || exit 1
    fi
    cd ..
}

function cmake_graph() {
    cmake_init
    echo -e " * cmake graphviz\n" && cd build && cmake --graphviz=cmake.dot .. && dot -Tpng -o cmake_dep.png cmake.dot && cd .. || exit 1
}

function cmake_doc() {
    cmake_init
    echo -e " * cmake doc\n" && cd build && make doc && cd .. || exit 1
}

function cmake_help() {
    cmake_init
    echo -e " * cmake help\n" && cd build && cmake .. -L && cd .. || exit 1
}

function cmake_exec() {
    cmake_init
    echo -e " * execute hydrogen\n" && cd build && ./src/gui/hydrogen $H2FLAGS && cd .. || exit 1
}

function cmake_tests() {
    cmake_init
    echo -e " * execute tests\n" && ./build/src/tests/tests&& cd .. || exit 1
}

function cmake_pkg() {
    cmake_init
    echo -e " * execute hydrogen\n" && cd build && make package_source && cd .. || exit 1
}

if [ $# -eq 0 ]; then
    echo "usage $0 [cmds list]"
    echo "cmds may be"
    echo "   r[m]     => all built, temp and cache files"
    echo "   c[lean]  => remove cache files"
    echo "   m[ake]   => launch the build process"
    echo "   d[oc]    => build html documentation"
    echo "   g[raph]  => draw a dependecies graph"
    echo "   h[elp]   => show the build options"
    echo "   x|exec   => execute hydrogen"
    echo "   t[ests]  => execute tests"
    echo "   p[kg]    => build source package"
    echo "ex: ./tool/cmake r m pkg x"
    exit 1
fi

for arg in $@; do
    case $arg in
        "c")
            cmd="cmake_clean"
            ;;
        "clean")
            cmd="cmake_${arg}"
            ;;
        "r")
            cmd="cmake_rm"
            ;;
        "rm")
            cmd="cmake_${arg}"
            ;;
        "m")
            cmd="cmake_make"
            ;;
        "make")
            cmd="cmake_${arg}"
            ;;
        "g")
            cmd="cmake_graph"
            ;;
        "graph")
            cmd="cmake_${arg}"
            ;;
        "d")
            cmd="cmake_doc"
            ;;
        "doc")
            cmd="cmake_${doc}"
            ;;
        "h")
            cmd="cmake_help"
            ;;
        "help")
            cmd="cmake_${arg}"
            ;;
        "x")
            cmd="cmake_exec"
            ;;
        "exec")
            cmd="cmake_${arg}"
            ;;
        "t")
            cmd="cmake_tests"
            ;;
        "tests")
            cmd="cmake_${arg}"
            ;;
        "p")
            cmd="cmake_pkg"
            ;;
        "pkg")
            cmd="cmake_${arg}"
            ;;
        *)
         echo "unknown command ${arg}" && exit 1
     esac
     $cmd
done
