.TH HYDROGEN "1" "October 17, 2025" "Hydrogen 2.0.0-pre-alpha" "User Commands"
.SH NAME
Hydrogen \- an advanced drum machine and step sequencer.
.SH SYNOPSIS
.PP
.B hydrogen
[options] [file]
.SH DESCRIPTION
.PP
\fBHydrogen\fR is both a drum sequencer for pattern-based programming and a drum
synth. Its simple yet feature-rich design makes it a versatile companion, be it
for quick practice at home, professional usage as fully-fledged drum machine in
your studio, or drum looper on steroids for your live performance.
.PP
Features:
.br
- First-class \fBMIDI\fR support
.br
- Highly customizable
.br
- Stable and performant
.br
- Loads of drumkits to choose from
.br
- In-depth control of instrument, sample, and note properties
.br
- High quality time-stretching and pitch shifting
.br
- Automate it using \fBMIDI\fR or \fBOSC\fR API
.SH OPTIONS
.TP
\fB\-d\fR, \fB\-\-driver\fR=[\fIAUDIO_DRIVER\fR]
Use the selected audio driver. The description of this option in the -\-help output contains all audio
drivers available on your system.
.TP
\fB\-s\fR, \fB\-\-song\fR=\fIFILE\fR
Load a song (\fI*.h2song\fR) at startup. Alternatively, you can just pass the filename without this option.
.TP
\fB\-p\fR, \fB\-\-playlist\fR=\fIFILE\fR
Load a playlist (\fI*.h2playlist\fR) at startup.
.TP
\fB\-k\fR, \fB\-\-kit\fR=\fIDRUMKIT_NAME\fR
Load a drumkit at startup.
.TP
\fB\-i\fR, \fB\-\-install\fR=\fIFILE\fR
Install a drumkit (\fI*.h2drumkit\fR).
.TP
\fB\-O\fR, \fB\-\-osc\-port\fR=\fIPORT\fR
Use custom OSC port.
.TP
\fB\-P\fR, \fB\-\-data\fR=\fIPATH\fR
Use an alternate system data path.
.TP
\fB\-\-user\-data\fR=\fIPATH\fR
Use an alternate user data path.
.TP
\fB\-\-config\fR=\fIPATH\fR
Use an alternate path to the \fIhydrogen.conf\fR file.
.TP
\fB\-\-layout\fR=\fILAYOUT\fR
UI layout. Either \fItabbed\fR or \fIsingle\fR (default).
.TP
\fB\-n\fR, \fB\-\-nosplash\fR
Hide splash screen.
.TP
\fB\-V\fR, \fB\-\-verbose\fR=[\fILEVEL\fR]
Print a lot of debugging info
.IP
Level, if present, may be \fINone\fR, \fIError\fR, \fIWarning\fR, \fIInfo\fR, or \fIDebug\fR.
.TP
\fB\-L\fR, \fB\-\-log\-file\fR=\fIFILE\fR
Use custom log file.
.TP
\fB\-T\fR, \fB\-\-log\-timestamps\fR
Add timestamps to all log messages.
.TP
\fB\-\-log\-colors\fR
Use ANSI colors in log messages (default).
.TP
\fB\-\-no\-log\-colors\fR
Suppress ANSI colors in log messages.
.TP
\fB\-c\fR, \fB\-\-connect\-via\-ipc\fR=\fIENDPOINT\fR
Connect to a headless Hydrogen engine via IPC. The endpoint must be provided
by a running \fBh2player\fR or plugin instance. This option runs Hydrogen in
editor mode without creating a local engine.
.TP
\fB\-v\fR, \fB\-\-version\fR
Show version info.
.TP
\fB\-h\fR, \fB\-\-help\fR
Show this help message.
.SH FILES
.TP
New installations of Hydrogen will follow XDG paths and create folders called \fIhydrogen\fR within the locations defined by the environmental variables:
.RS
.PP
\(bu $XDG_CONFIG_HOME (defaults to \fI~/.config/\fR)
.PP
\(bu $XDG_CACHE_HOME  (defaults to \fI~/.cache/\fR)
.PP
\(bu $XDG_DATA_HOME   (defaults to \fI~/.local/share/\fR)
.RE
.PP
Previous versions created a folder within the home directory called
\fI~/.hydrogen\fR (note that this location could have been altered by a
compilation option). If the old folder is found, it takes precedence over the
XDG paths.
.PP
\fB$XDG_DATA_HOME/hydrogen/\fR (new)
.br
\fB$HOME/.hydrogen/data/\fR (old; takes precedence)
.RS
.TP
\fBdrumkits/\fR
User-level drumkit folder. All drumkits you download via the online import as well as those you created manually will end up here. A portable version of a drumkit - the \fI.h2drumkit\fR tar archive file - can included into this folder using the \-\-install option. Drumkits residing in this folder will be shown in the Sound Library by default.
.TP
\fBpatterns/\fR
Patterns - \fI.h2pattern\fR XML files - residing in this folder will be shown in the Sound Library by default.
.TP
\fBplaylists/\fR
This folder may have been original designed for holding \fI.h2playlist\fR XML files. But it does not serve any special purpose anymore and you can put them where ever you want.
.TP
\fBplugins/\fR
In here you can put \fBLADSPA\fR plugins to be used by Hydrogen, which are not within \fBLADSPA_PATH\fR.
.TP
\fBscripts/\fR
Playlists in Hydrogen can be configured to run a \fBBASH\fR script before loading a particular song. This folder may have been original designed for holding those script but you can put them where ever you want.
.TP
\fBsongs/\fR
Songs - \fI.h2song\fR XML files - residing in this folder will be shown in the Sound Library by default.
.TP
\fBthemes/\fR
You can change colors, fonts, and many more in Hydrogen. These custom settings can be stored as \fI.h2theme\fR XML files in here by exporting the current theme in the Preferences dialog.
.SH CONFIGURATION
.PP
In new installations of Hydrogen the configuration file will be located at \fI$XDG_CONFIG_HOME/hydrogen/hydrogen.conf\fR. In case an old one at \fI~/.hydrogen/hydrogen.conf\fR is present, it takes precedence.
.SH ENVIRONMENT
.TP
\fBLADSPA_PATH\fR
Path to \fBLADSPA\fR plugins.
.TP
\fBXDG_CONFIG_HOME\fR
Defines the folder that contains the configuration in \fIhydrogen/hydrogen.conf\fR.
.TP
\fBXDG_CACHE_HOME\fR
Will be used to store session data.
.TP
\fBXDG_DATA_HOME\fR
Will contain most user-level data within the subfolder \fIhydrogen\fR.
.SH BUGS & FEATURES REQUEST
.PP
If you find any bug or if you would like to propose a new feature, please report it to https://github.com/hydrogen-music/hydrogen/issues
.SH AUTHORS
.PP
The hydrogen development team. See complete list at Hydrogen's "About" Dialog. You can contact them at <hydrogen-devel@lists.sourceforge.net>.
.TP
Subscription to the mailing list can be done here :
.br
http://lists.sourceforge.net/lists/listinfo/hydrogen-devel .
.SH SEE ALSO
A CLI tool for exporting songs and batch processing drumkits
.RS
\fBh2cli\fR(1)
.RE
.PP
A player Hydrogen-based songs on the command line
.RS
\fBh2player\fR(1)
.RE
.SH COPYRIGHT AND LICENSE
\fBCopyright (C)\fR 2002\-2008 Alessandro Cominu
.br
\fBCopyright (C)\fR 2008\-2026 The hydrogen development team
.PP
\fBHydrogen\fR is free software; you can redistribute it and/or modify it under the terms of the GPL version 2 or later.
